---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: no
  vars:
    name: "public-compute-instance"
    region: us-east-1
    access_key: access_key
    secret_key: secret_key
    key_name: "prod-ssh-key"
    vpc_subnet_id: subnet-5ca1ab1e
    instance_type: c5.large
    security_group: default
    network:
      assign_public_ip: true
    image_id: ami-123456
    tags:
      Environment: Testing
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: Myinstance
        access_key: AKIA6HDJY6E7ZEGENQX6
        secret_key: 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
        region: us-east-1
        key_name: EC2key
        vpc_subnet_id: subnet-03c360d07fef2f943
        instance_type: t2.micro
        security_group: sg-0209f1d0fdf2cfb4b
        network:
          assign_public_ip: true
        image_id: ami-00c39f71452c08778
        tags:
          Environment: Testing

      register: ec2
